baseURL = "http://blog.mitsociety.id/"
languageCode = "id-id"
title = "Blog Muhammadiyah IT Society"

theme = "minimo"

[taxonomies]
author = "authors"

[params.widgets]
header = ["breadcrumbs"]
homepage = ["recent_posts"]
sidebar = ["about","taxonomy_cloud"]
footer = ["social_menu"]
